-- MySQL Script generated by MySQL Workbench
-- 05/25/17 21:12:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema POS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema POS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `POS` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema pos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pos` DEFAULT CHARACTER SET utf8 ;
USE `POS` ;

-- -----------------------------------------------------
-- Table `POS`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `nit` INT NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `tipoCliente` INT NULL COMMENT '',
  PRIMARY KEY (`idCliente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`TipoVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`TipoVenta` (
  `idTipoVenta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombrePago` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTipoVenta`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigoProducto` VARCHAR(45) NULL COMMENT '',
  `nombreProducto` VARCHAR(45) NULL COMMENT '',
  `precioProducto` DECIMAL(10,2) NULL COMMENT '',
  `fechaVencimiento` DATE NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  PRIMARY KEY (`idProducto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cliente` INT NULL COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `producto` INT NULL COMMENT '',
  `monto` DECIMAL(15,2) NULL COMMENT '',
  `tipoVenta` INT NULL COMMENT '',
  PRIMARY KEY (`idVenta`)  COMMENT '',
  INDEX `cliente_idx` (`cliente` ASC)  COMMENT '',
  INDEX `tipoVenta_idx` (`tipoVenta` ASC)  COMMENT '',
  INDEX `producto_idx` (`producto` ASC)  COMMENT '',
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `POS`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoVenta`
    FOREIGN KEY (`tipoVenta`)
    REFERENCES `POS`.`TipoVenta` (`idTipoVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto`
    FOREIGN KEY (`producto`)
    REFERENCES `POS`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`TipoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`TipoPago` (
  `idTipoPago` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombrePago` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`idTipoPago`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`formapago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`formapago` (
  `idformapago` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombrepago` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idformapago`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`DetalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`DetalleVenta` (
  `idDetalleVenta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `TipoPago` INT NULL COMMENT '',
  `registro` INT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `venta` INT NULL COMMENT '',
  `formaPago` INT NULL COMMENT '',
  PRIMARY KEY (`idDetalleVenta`)  COMMENT '',
  INDEX `venta_idx` (`venta` ASC)  COMMENT '',
  INDEX `tipopago_idx` (`TipoPago` ASC)  COMMENT '',
  INDEX `formapago_idx` (`formaPago` ASC)  COMMENT '',
  CONSTRAINT `venta`
    FOREIGN KEY (`venta`)
    REFERENCES `POS`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipopago`
    FOREIGN KEY (`TipoPago`)
    REFERENCES `POS`.`TipoPago` (`idTipoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `formapago`
    FOREIGN KEY (`formaPago`)
    REFERENCES `POS`.`formapago` (`idformapago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`Devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`Devolucion` (
  `idDevolucion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombredevolucion` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`idDevolucion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`Status` (
  `idStatus` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreStatus` VARCHAR(75) NULL COMMENT '',
  PRIMARY KEY (`idStatus`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`DetalleDevolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`DetalleDevolucion` (
  `idDetalleDevolucion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `detalleVenta` INT NULL COMMENT '',
  `cantidadproducto` INT NULL COMMENT '',
  `devolucion` INT NULL COMMENT '',
  `estatus` INT NULL COMMENT '',
  `producto` INT NULL COMMENT '',
  PRIMARY KEY (`idDetalleDevolucion`)  COMMENT '',
  INDEX `detalleventa_idx` (`detalleVenta` ASC)  COMMENT '',
  INDEX `cantidadproducto_idx` (`producto` ASC)  COMMENT '',
  INDEX `devolucion_idx` (`devolucion` ASC)  COMMENT '',
  INDEX `estatus_idx` (`estatus` ASC)  COMMENT '',
  CONSTRAINT `detalleventa`
    FOREIGN KEY (`detalleVenta`)
    REFERENCES `POS`.`DetalleVenta` (`idDetalleVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cantidadproducto`
    FOREIGN KEY (`producto`)
    REFERENCES `POS`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `devolucion`
    FOREIGN KEY (`devolucion`)
    REFERENCES `POS`.`Devolucion` (`idDevolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estatus`
    FOREIGN KEY (`estatus`)
    REFERENCES `POS`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`Proveedores` (
  `idProveedores` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreProveedor` VARCHAR(45) NULL COMMENT '',
  `nit` INT NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `telefono` INT NULL COMMENT '',
  PRIMARY KEY (`idProveedores`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `proveedor` INT NULL COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `Producto` INT NULL COMMENT '',
  `monto` DECIMAL(15,2) NULL COMMENT '',
  PRIMARY KEY (`idcompra`)  COMMENT '',
  INDEX `proveedor_idx` (`proveedor` ASC)  COMMENT '',
  INDEX `producto_idx` (`Producto` ASC)  COMMENT '',
  CONSTRAINT `provee`
    FOREIGN KEY (`proveedor`)
    REFERENCES `POS`.`Proveedores` (`idProveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `produc`
    FOREIGN KEY (`Producto`)
    REFERENCES `POS`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POS`.`detalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POS`.`detalleCompra` (
  `iddetalleCompra` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipoPago` INT NULL COMMENT '',
  `registro` INT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `compra` INT NULL COMMENT '',
  `formaPago` INT NULL COMMENT '',
  PRIMARY KEY (`iddetalleCompra`)  COMMENT '',
  INDEX `tipopago_idx` (`tipoPago` ASC)  COMMENT '',
  INDEX `formapago_idx` (`formaPago` ASC)  COMMENT '',
  INDEX `compra_idx` (`compra` ASC)  COMMENT '',
  CONSTRAINT `fktipopago`
    FOREIGN KEY (`tipoPago`)
    REFERENCES `POS`.`TipoPago` (`idTipoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkformapago`
    FOREIGN KEY (`formaPago`)
    REFERENCES `POS`.`formapago` (`idformapago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkcompra`
    FOREIGN KEY (`compra`)
    REFERENCES `POS`.`compra` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pos` ;

-- -----------------------------------------------------
-- Table `pos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `apellido` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `nit` INT(11) NULL DEFAULT NULL COMMENT '',
  `direccion` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `tipoCliente` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idCliente`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pos`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`producto` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `codigoProducto` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `nombreProducto` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `precioProducto` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '',
  `fechaVencimiento` DATE NULL DEFAULT NULL COMMENT '',
  `cantidad` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idProducto`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pos`.`formapago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`formapago` (
  `idformapago` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombrepago` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idformapago`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pos`.`tipopago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`tipopago` (
  `idTipoPago` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombrePago` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idTipoPago`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pos`.`tipoventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`tipoventa` (
  `idTipoVenta` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombrePago` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idTipoVenta`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pos`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`venta` (
  `idVenta` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `cliente` INT(11) NULL DEFAULT NULL COMMENT '',
  `fecha` DATE NULL DEFAULT NULL COMMENT '',
  `producto` INT(11) NULL DEFAULT NULL COMMENT '',
  `monto` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '',
  `tipoVenta` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idVenta`)  COMMENT '',
  INDEX `cliente_idx` (`cliente` ASC)  COMMENT '',
  INDEX `tipoVenta_idx` (`tipoVenta` ASC)  COMMENT '',
  INDEX `producto_idx` (`producto` ASC)  COMMENT '',
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `pos`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto`
    FOREIGN KEY (`producto`)
    REFERENCES `pos`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoVenta`
    FOREIGN KEY (`tipoVenta`)
    REFERENCES `pos`.`tipoventa` (`idTipoVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pos`.`detalleventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`detalleventa` (
  `idDetalleVenta` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `TipoPago` INT(11) NULL DEFAULT NULL COMMENT '',
  `registro` INT(11) NULL DEFAULT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `venta` INT(11) NULL DEFAULT NULL COMMENT '',
  `formaPago` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idDetalleVenta`)  COMMENT '',
  INDEX `venta_idx` (`venta` ASC)  COMMENT '',
  INDEX `tipopago_idx` (`TipoPago` ASC)  COMMENT '',
  INDEX `formapago_idx` (`formaPago` ASC)  COMMENT '',
  CONSTRAINT `formapago`
    FOREIGN KEY (`formaPago`)
    REFERENCES `pos`.`formapago` (`idformapago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipopago`
    FOREIGN KEY (`TipoPago`)
    REFERENCES `pos`.`tipopago` (`idTipoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `venta`
    FOREIGN KEY (`venta`)
    REFERENCES `pos`.`venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pos`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`devolucion` (
  `idDevolucion` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombredevolucion` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idDevolucion`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pos`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`status` (
  `idStatus` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreStatus` VARCHAR(75) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idStatus`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pos`.`detalledevolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`detalledevolucion` (
  `idDetalleDevolucion` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `detalleVenta` INT(11) NULL DEFAULT NULL COMMENT '',
  `cantidadproducto` INT(11) NULL DEFAULT NULL COMMENT '',
  `devolucion` INT(11) NULL DEFAULT NULL COMMENT '',
  `estatus` INT(11) NULL DEFAULT NULL COMMENT '',
  `producto` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idDetalleDevolucion`)  COMMENT '',
  INDEX `detalleventa_idx` (`detalleVenta` ASC)  COMMENT '',
  INDEX `cantidadproducto_idx` (`producto` ASC)  COMMENT '',
  INDEX `devolucion_idx` (`devolucion` ASC)  COMMENT '',
  INDEX `estatus_idx` (`estatus` ASC)  COMMENT '',
  CONSTRAINT `cantidadproducto`
    FOREIGN KEY (`producto`)
    REFERENCES `pos`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `detalleventa`
    FOREIGN KEY (`detalleVenta`)
    REFERENCES `pos`.`detalleventa` (`idDetalleVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `devolucion`
    FOREIGN KEY (`devolucion`)
    REFERENCES `pos`.`devolucion` (`idDevolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estatus`
    FOREIGN KEY (`estatus`)
    REFERENCES `pos`.`status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pos`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`proveedores` (
  `idProveedores` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreProveedor` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `nit` INT(11) NULL DEFAULT NULL COMMENT '',
  `direccion` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `telefono` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idProveedores`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
